# Generated by Django 4.0.4 on 2022-05-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_content', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('voice', 'Голосовое')], max_length=5, verbose_name='Тип контента')),
                ('loader_id', models.BigIntegerField(verbose_name='ID юзера')),
                ('file_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID файла')),
                ('moderated', models.BooleanField(verbose_name='Проверенный')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='ID юзера')),
                ('banned', models.BooleanField(verbose_name='Забанен')),
                ('last_photo', models.BigIntegerField(verbose_name='ID последнего фото')),
                ('last_video', models.BigIntegerField(verbose_name='ID последнего видео')),
                ('last_voice', models.BigIntegerField(verbose_name='ID последнего голосового')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
