# Generated by Django 4.0.4 on 2022-05-23 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file_id',
            field=models.CharField(db_index=True, help_text='ID файла для получения его с сервера Telegram', max_length=255, unique=True, verbose_name='ID файла'),
        ),
        migrations.AlterField(
            model_name='content',
            name='loader_id',
            field=models.BigIntegerField(help_text='ID пользователя который добавил этот файл', verbose_name='ID юзера'),
        ),
        migrations.AlterField(
            model_name='content',
            name='moderated',
            field=models.BooleanField(help_text='Если контент отмечен как проверенный, то он попадает пользователям в выдачу.', verbose_name='Проверенный'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banned',
            field=models.BooleanField(help_text='Забанен ли юзер', verbose_name='Забанен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_photo',
            field=models.BigIntegerField(help_text='ID последнего полученного фото', verbose_name='ID последнего фото'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_video',
            field=models.BigIntegerField(help_text='ID последнего полученного видео', verbose_name='ID последнего видео'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_voice',
            field=models.BigIntegerField(help_text='ID последнего полученного голосового сообщения', verbose_name='ID последнего голосового'),
        ),
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_user_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
