# Generated by Django 4.0.4 on 2022-05-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0002_alter_content_file_id_alter_content_loader_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_name_user',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Имя пользователя'),
        ),
    ]
