# Generated by Django 4.0.4 on 2022-05-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0003_user_tg_name_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_username_user',
            field=models.CharField(default='@Unknown', max_length=255, verbose_name='Юзернейм пользователя'),
        ),
    ]
