# Generated by Django 4.0.4 on 2022-05-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0004_user_tg_username_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_banned',
            field=models.BooleanField(default=False, help_text='Закрыть доступ к боту', verbose_name='Полностью забанен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False, help_text='Забанен ли юзер', verbose_name='Забанен'),
        ),
    ]
