# Generated by Django 4.0.5 on 2022-06-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager', '0005_user_full_banned_alter_user_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Число дизлайков'),
        ),
    ]
